[package]
name = "ip2proxy-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ip2location = "0.3.5"
rocket = { version = "0.5.0-rc.2", features = ["json"] }